# Generated by Django 3.2.18 on 2023-04-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_user1_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blahblah',
            field=models.CharField(default='True', max_length=20),
        ),
    ]
